export const NEST_BOOT = 'NEST_BOOT';
export const NEST_CONSUL = 'NEST_CONSUL';
export const NEST_CONSUL_CONFIG = 'NEST_CONSUL_CONFIG';
export const NEST_CONSUL_LOADBALANCE = 'NEST_CONSUL_LOADBALANCE';
export const NEST_CONSUL_SERVICE = 'NEST_CONSUL_SERVICE';
export const NEST_LOGGER = 'NEST_LOGGER';
export const NEST_GATEWAY = 'NEST_GATEWAY';
export const NEST_FEIGN = 'NEST_FEIGN';
export const LOCAL = 'LOCAL';
export const NEST_COMMON = 'NEST_COMMON';

export const NEST_BOOT_PROVIDER = 'NEST_BOOT_PROVIDER';
export const NEST_CONSUL_PROVIDER = 'NEST_CONSUL_PROVIDER';
export const NEST_CONSUL_CONFIG_PROVIDER = 'NEST_CONSUL_CONFIG_PROVIDER';
export const NEST_CONSUL_SERVICE_PROVIDER = 'NEST_CONSUL_SERVICE_PROVIDER';
export const NEST_CONSUL_LOADBALANCE_PROVIDER = 'NEST_CONSUL_LOADBALANCE_PROVIDER';
export const NEST_FEIGN_PROVIDER = 'NEST_FEIGN_PROVIDER';
export const NEST_MEMCACHED_PROVIDER = 'NEST_MEMCACHED_PROVIDER';
export const NEST_LOGGER_PROVIDER = 'NEST_LOGGER_PROVIDER';
export const NEST_GATEWAY_PROVIDER = 'NEST_GATEWAY_PROVIDER';
export const NEST_TYPEORM_LOGGER_PROVIDER = 'NEST_TYPEORM_LOGGER_PROVIDER';
export const NEST_COMMON_PROVIDER = 'NEST_COMMON_PROVIDER';

export const CRITICAL = 'critical';
export const PASSING = 'passing';
export const WARNING = 'warning';
