export const CONSUL_OPTIONS_PROVIDER = 'CONSUL_OPTIONS_PROVIDER';

export const CONSUL_WATCH_KV_NAME = 'CONSUL_WATCH_KV_NAME';
export const CONSUL_WATCH_KV_OPTIONS = 'CONSUL_WATCH_KV_OPTIONS';
export const CONSUL_WATCH_KV_PROPERTY = 'CONSUL_WATCH_KV_PROPERTY';
