export const BOOT_OPTIONS_PROVIDER = 'BOOT_OPTIONS_PROVIDER';

export const BOOT_VALUE_NAME = 'BOOT_VALUE_NAME';
export const BOOT_VALUE_DEFAULTS = 'BOOT_VALUE_DEFAULTS';
export const BOOT_VALUE_PROPERTY = 'BOOT_VALUE_PROPERTY';
