export const CONFIG_OPTIONS_PROVIDER = 'CONFIG_OPTIONS_PROVIDER';

export const CONFIG_VALUE_NAME = 'CONFIG_VALUE_NAME';
export const CONFIG_VALUE_DEFAULTS = 'CONFIG_VALUE_DEFAULTS';
export const CONFIG_VALUE_PROPERTY = 'CONFIG_VALUE_PROPERTY';
