export const SCHEDULER_NAME = 'SCHEDULER_NAME';
export const SCHEDULER_TYPE = 'SCHEDULER_TYPE';
export const SCHEDULER_OPTIONS = 'SCHEDULER_OPTIONS';

export const SCHEDULE_CRON_OPTIONS = 'SCHEDULE_CRON_OPTIONS';
export const SCHEDULE_INTERVAL_OPTIONS = 'SCHEDULE_INTERVAL_OPTIONS';
export const SCHEDULE_TIMEOUT_OPTIONS = 'SCHEDULE_TIMEOUT_OPTIONS';
export const SCHEDULE_LOCKER = 'SCHEDULE_LOCKER';
export const SCHEDULE_BACKEND = 'SCHEDULE_BACKEND';
